const MAXIMUM_USERS_FOR_ONE_ROOM = 4;
const SECONDS_TIMER_BEFORE_START_GAME = 5;
const SECONDS_FOR_GAME = 160;

export { MAXIMUM_USERS_FOR_ONE_ROOM, SECONDS_FOR_GAME, SECONDS_TIMER_BEFORE_START_GAME };
